import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {NftMarketplaceProvider} from "../../context/NftMarketplaceContext"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'BlueBeetle',
  description: 'Generated by create next app',
}

import { Navbar } from '@/components/component.index'
import {Footer} from '@/components/component.index'
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>\
      <NftMarketplaceProvider>
      <Navbar/>
      {children}
      <Footer/>
      </NftMarketplaceProvider>
      </body>
    </html>
  )
}
